version: '3.8'

networks:
  lake-solution:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    networks:
      - lake-solution

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
    networks:
      - lake-solution
