apiVersion: v1
kind: Secret
metadata:
  name: private-stack-lake
  namespace: gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/matbragan/data-lake-solution
  password: <FIXIT>
  username: argocd